import type { NewHackathon } from "./schema";

/**
 * Seed dates are generated relative to "today" so the demo data always contains
 * genuinely upcoming events with open application windows. Replace this seed with
 * real events via the admin panel.
 */
const DAY = 86_400_000;
const iso = (offsetDays: number) =>
  new Date(Date.now() + offsetDays * DAY).toISOString().slice(0, 10);
const ago = (days: number) => new Date(Date.now() - days * DAY);

export const seedHackathons: NewHackathon[] = [
  {
    slug: "global-hack-week-2024",
    title: "Global Hack Week 2024",
    summary:
      "A week-long global hackathon bringing together builders across Africa and beyond.",
    description:
      "A week-long global hackathon bringing together builders across Africa and beyond to tackle open-ended challenges across web3, AI and fintech tracks.",
    theme: "Web3",
    tags: "Web3,Open Source",
    status: "applications_open",
    adminStatus: "published",
    track: "Tech Track",
    participantCount: 142,
    startDate: iso(30),
    endDate: iso(33),
    applicationDeadline: iso(20),
    location: "JKUAT Main Campus / Virtual",
    locationType: "hybrid",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/ai-for-africa-2024.jpg",
    sortOrder: 1,
    applicationMode: "team",
    minTeamSize: 2,
    maxTeamSize: 5,
    updatedAt: ago(12),
  },
  {
    slug: "greentech-innovators",
    title: "GreenTech Innovators",
    summary: "Draft event for sustainability-focused builders.",
    description:
      "Draft event for sustainability-focused builders across climate, energy, and circular economy tracks.",
    theme: "Climate",
    tags: "Climate,Sustainability",
    status: "starts_soon",
    adminStatus: "draft",
    track: "Sustainability",
    participantCount: 0,
    startDate: iso(55),
    endDate: iso(57),
    applicationDeadline: iso(45),
    location: "Nairobi Tech Hub",
    locationType: "in_person",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/climatetech-innovators.jpg",
    sortOrder: 2,
    updatedAt: ago(20),
  },
  {
    slug: "ai-for-good-summit",
    title: "AI For Good Summit",
    summary: "Build AI solutions for health, agriculture and civic-tech.",
    description:
      "Build AI solutions addressing health, agriculture and civic-tech problems with mentor support from the Open AI track.",
    theme: "AI/ML",
    tags: "AI/ML,HealthTech,AgriTech",
    status: "applications_open",
    adminStatus: "published",
    track: "Open AI Track",
    participantCount: 89,
    startDate: iso(14),
    endDate: iso(16),
    applicationDeadline: iso(7),
    location: "Fully Virtual",
    locationType: "virtual",
    externalRegUrl: "https://example.com/register/ai-for-good",
    imageUrl: "/images/hackathons/ai-for-africa-2024.jpg",
    sortOrder: 3,
    applicationMode: "team",
    minTeamSize: 3,
    maxTeamSize: 6,
    updatedAt: ago(6),
  },
  {
    slug: "fintech-challenge-2023",
    title: "FinTech Challenge '23",
    summary: "2023 fintech edition — now archived.",
    description:
      "2023 fintech edition — mobile money, agent networks, cross-border payments. Now archived.",
    theme: "FinTech",
    tags: "FinTech",
    status: "ended",
    adminStatus: "archived",
    track: "Completed",
    participantCount: 312,
    startDate: iso(-600),
    endDate: iso(-596),
    applicationDeadline: iso(-615),
    location: "JKUAT Main Campus",
    locationType: "in_person",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/fintech-frontier.jpg",
    sortOrder: 4,
    updatedAt: ago(202),
  },
  {
    slug: "ai-for-africa-2024",
    title: "AI for Africa 2024",
    summary: "Build AI-driven solutions for African challenges.",
    description:
      "Build AI-driven solutions addressing unique challenges across the African continent in healthcare, agriculture, and education.",
    theme: "AI/ML",
    tags: "AI/ML",
    status: "applications_open",
    adminStatus: "published",
    track: "AI/ML Track",
    participantCount: 120,
    startDate: iso(45),
    endDate: iso(47),
    applicationDeadline: iso(35),
    location: "JKUAT Main Campus / Virtual",
    locationType: "hybrid",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/ai-for-africa-2024.jpg",
    sortOrder: 5,
    applicationMode: "team",
    minTeamSize: 2,
    maxTeamSize: 4,
    updatedAt: ago(17),
  },
  {
    slug: "fintech-frontier",
    title: "FinTech Frontier",
    summary: "DeFi, micro-lending, mobile-first banking.",
    description:
      "Innovate the future of financial inclusion with decentralized finance, micro-lending platforms, and mobile-first banking tools.",
    theme: "FinTech",
    tags: "FinTech,Web3",
    status: "applications_open",
    adminStatus: "published",
    track: "DeFi Track",
    participantCount: 76,
    startDate: iso(60),
    endDate: iso(63),
    applicationDeadline: iso(50),
    location: "Fully Virtual",
    locationType: "virtual",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/fintech-frontier.jpg",
    sortOrder: 6,
    applicationMode: "team",
    minTeamSize: 2,
    maxTeamSize: 5,
    updatedAt: ago(22),
  },
  {
    slug: "climatetech-innovators",
    title: "ClimateTech Innovators",
    summary: "Sustainable tech for climate change mitigation.",
    description:
      "Developing sustainable tech solutions for climate change mitigation, sustainable agriculture, and clean energy access.",
    theme: "Climate",
    tags: "Climate,AgriTech",
    status: "starts_soon",
    adminStatus: "published",
    track: "Sustainability",
    participantCount: 54,
    startDate: iso(90),
    endDate: iso(92),
    applicationDeadline: iso(80),
    location: "Nairobi Tech Hub",
    locationType: "in_person",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/climatetech-innovators.jpg",
    sortOrder: 7,
    applicationMode: "individual",
    minTeamSize: 1,
    maxTeamSize: 1,
    updatedAt: ago(32),
  },
  {
    slug: "healthtech-sprint",
    title: "HealthTech Sprint",
    summary: "Draft event for community health and telemedicine.",
    description:
      "Draft event for community health, telemedicine and medical supply chain solutions.",
    theme: "HealthTech",
    tags: "HealthTech,AI/ML",
    status: "applications_open",
    adminStatus: "draft",
    track: "Health",
    participantCount: 0,
    startDate: iso(120),
    endDate: iso(122),
    applicationDeadline: iso(110),
    location: "Nairobi Tech Hub",
    locationType: "hybrid",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/climatetech-innovators.jpg",
    sortOrder: 8,
    updatedAt: ago(42),
  },
  {
    slug: "agritech-open-2024",
    title: "AgriTech Open 2024",
    summary: "For smallholder farmers and market linkage.",
    description:
      "Published agritech edition focused on smallholder farmers, yield prediction and market linkage.",
    theme: "AgriTech",
    tags: "AgriTech,AI/ML",
    status: "applications_open",
    adminStatus: "published",
    track: "Agriculture",
    participantCount: 61,
    startDate: iso(25),
    endDate: iso(27),
    applicationDeadline: iso(18),
    location: "JKUAT Main Campus",
    locationType: "in_person",
    externalRegUrl: "",
    imageUrl: "/images/resources/agriconnect-dashboard.jpg",
    sortOrder: 9,
    updatedAt: ago(10),
  },
  {
    slug: "web3-builders-hack-2023",
    title: "Web3 Builders Hack 2023",
    summary: "2023 web3 edition, now completed.",
    description: "2023 web3 edition — completed, with results and winners published.",
    theme: "Web3",
    tags: "Web3",
    status: "ended",
    adminStatus: "published",
    track: "Completed",
    participantCount: 198,
    startDate: iso(-400),
    endDate: iso(-398),
    applicationDeadline: iso(-415),
    location: "Fully Virtual",
    locationType: "virtual",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/ai-for-africa-2024.jpg",
    sortOrder: 10,
    updatedAt: ago(135),
  },
  {
    slug: "edtech-pilot",
    title: "EdTech Pilot",
    summary: "Draft of a new EdTech hackathon.",
    description: "Draft of a new EdTech-focused hackathon for local schools and universities.",
    theme: "AI/ML",
    tags: "AI/ML,EdTech",
    status: "starts_soon",
    adminStatus: "draft",
    track: "Education",
    participantCount: 0,
    startDate: iso(150),
    endDate: iso(152),
    applicationDeadline: iso(140),
    location: "Virtual",
    locationType: "virtual",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/fintech-frontier.jpg",
    sortOrder: 11,
    updatedAt: ago(52),
  },
  {
    slug: "open-source-sprint-2023",
    title: "Open Source Sprint 2023",
    summary: "Community open source sprint.",
    description:
      "Past community sprint contributing to open source projects that power African startups.",
    theme: "Web3",
    tags: "Web3,Open Source",
    status: "ended",
    adminStatus: "published",
    track: "Open Source",
    participantCount: 47,
    startDate: iso(-300),
    endDate: iso(-298),
    applicationDeadline: iso(-315),
    location: "JKUAT Main Campus",
    locationType: "in_person",
    externalRegUrl: "",
    imageUrl: "/images/hackathons/ai-for-africa-2024.jpg",
    sortOrder: 12,
    updatedAt: ago(102),
  },
];
